[package]
name = "od_tools"
version = "2.0.0"
edition = "2024"
license-file = "LICENSE"
description = "OpenDominion Sim Generator"
homepage = "https://github.com/tamadamas/od_tools"
repository = "https://github.com/tamadamas/od_tools"
readme = "README.md"

[dependencies]
# For reading .xlsx/.xlsm files
calamine = { version = "0.31.0", features = ["chrono", "dates"] }

# For date and time manipulation
chrono = "0.4.42"

# For parsing command-line arguments
clap = { version = "4.5.52", features = ["derive"] }

derive = "1.0.0"
# Static HashMap
phf = { version = "0.13.1", features = ["macros"] }
